locale: "en-US"

# Custom chat format - use <player> for player name, <message> for message
# There is also PlaceholderAPI support with <papi:NAME OF PLACEHOLDER> for example <papi:luckperms_prefix>
  # You can use %papi% if you use MiniMessage in your placeholder
# Use MiniMessage
chat-format:
  enabled: true
  format: "<gray><player> <dark_gray>| <white><message>"
  name-hover:
    message:
      enabled: true
      format: |
        <gradient:#2fa4c4:#2fbfc4:#2fc4a9>HyChat</gradient>
        <dark_gray>| <gray>Player: <white><player>
        <dark_gray>| <gray>Message: <white><message>
        <dark_gray>| <gray>Rank: <white><papi:luckperms_prefix>
    on-click:
      enabled: true
      action: "suggest_command"
      value: "/msg <player> "

# Clickable links in chat
# Allows to click on links and open them in browser
# If you want to force enable, use: hychat.clickable-links.bypass permission
clickable-links: true

# Mentioning players in chat
# Mention starts with @ (@hyro, @hychat)
# Allows to mention players in chat
mention-system:
  enabled: true
  # Placeholder: <player> for player name
  highlight-color: "<gradient:#2fa4c4:#2fbfc4:#2fc4a9><player></gradient:#2fa4c4:#2fbfc4:#2fc4a9>"

# No chat reports settings
# With the chat format, messages are already automatically made as system messages, but this can disable the popup :)
# WORKS ONLY ON 1.19.2
no-chat-reports:
  enabled: false
  enforce-secure-chat: false
  strip-signature: false
  # Not required because chat reports are disabled
  send-header-chat-packet: true

  # Join and leave messages
  # You can configure messages in the lang file
  # If you want to disable join and leave messages for specific players, use the permission
  # "hychat.join-and-leave.bypass-join"
  # "hychat.join-and-leave.bypass-leave"
join-and-leave:
  # Enable join messages
  join-enabled: true
  # Enable leave messages
  leave-enabled: true

# Anti-spam settings
# If you want to bypass antispam use "hychat.anti-spam.bypass"
anti-spam:
  # Enable antispam
  enabled: true
  # How many messages can be sent in the time interval (in milliseconds)
  # You can override this with the permission "hychat.anti-spam.cooldown.X"
  cooldown: 5000
  # What to do?
  # You can list commands to execute or use
    # "hychat::cancel" -> Block the message / Cancel event
    # "hychat::notify" -> Notify the admins (hychat.anti-spam.notify)
    # "hychat::send-message" -> Send a message to the player
  # Papi is supported, HERE USE %PAPI% NOT <papi:PAPI> like in chatformat or lang file
  actions:
    - "hychat::send-message"
    - "hychat::cancel"

# Anti-swear settings
# If you want to bypass antiswear use "hychat.anti-swear.bypass"
anti-swear:
  # Enable antiswear
  enabled: true
  # Check jaro winkler distance
  # If the distance is lower than the threshold, the message will be blocked
  # Jaro–Winkler distance is a string metric measuring an edit distance between two sequences. It is a variant proposed in 1990 by William E. Winkler of the Jaro distance metric
  jaro-winkler-distance:
    check: true
    threshold: 0.9
  # Check levenshtein distance
  # If the distance is lower than the threshold, the message will be blocked
  # Levenshtein distance is a string metric for measuring the difference between two sequences
  levenshtein-distance:
    check: true
    threshold: 0.8
  # List of words to block
  # You can override this with the permission "hychat.anti-swear.bypass.X"
  blocked-words:
    - "shit"
    - "trash"
    # What to do?
    # You can list commands to execute or use
    # "hychat::cancel" -> Block the message / Cancel event
    # "hychat::notify" -> Notify the admins (hychat.anti-swear.notify)
    # "hychat::send-message" -> Send a message to the player
  # Papi is supported, HERE USE %PAPI% NOT <papi:PAPI> like in chatformat or lang file
  actions:
    - "hychat::send-message"
    - "hychat::notify"
    - "hychat::cancel"

actions:
  notify:
    minecraft:
      anti-spam:
        enabled: false # Configure message in lang file in specific module
      anti-swear:
        enabled: true # Configure message in lang file in specific module
    discord:
      anti-spam:
        enabled: false
        url: "https://discord.com/api/webhooks/..."
      anti-swear:
        enabled: true
        url: "https://discord.com/api/webhooks/..."

# Send some metrics into bstats (https://bstats.org/plugin/bukkit/HyChat/17003)
# Also look into HyLib configuration
send-metrics: true

# Please, don't modify this version. It's used for internal purposes.
config-version: 4
