name: @name@
version: @version@
description: @description@
main: me.xhyrom.hychat.HyChat
author: xHyroM#2815
api-version: 1.19
softdepend:
  - PlaceholderAPI
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot

depend:
  - hylib-bukkit